version: '3.1'

services: 
    mongo:
        image: mongo
        restart: always
        environment: 
            MONGO_INITDB_DATABASE: restful_api
        volumes:
             - ./data:/data/db
        ports: 
            - 27017:27017
                
    app:
        build: 
            context: .
            dockerfile: Dockerfile 
        ports:
            - 3000:3000
        depends_on: 
            - mongo